### ISSUE TITLE
theano_utils

### ISSUE THREAD

**Issue by elbamos** [wuaalb/keras_extensions#1]
Hi.  I'm trying to use the RBM extension, but getting an error that theano_utils can't be found.  Surprisingly, since it seemed that theano_utils was part of keras, Google is not being helpful in resolving the issue.  

Can you help?

Also - are you continuing to actively develop this?  For a project, I'm interested in modifying it to support training with datasets that can't fit entirely in GPU and multiple layers.

**Comment by wuaalb** [comment]
The problem is that Keras is rapidly evolving and therefore extensions such as this one frequently need to be modified to keep up.

I'm guessing the problem with `theano_utils` is that current Keras has abstracted the Theano/TensorFlow backend, so that file probably doesn't exist anymore.
Unfortunately, I don't think this will be the only problem, so it'll need a bit of work to get it working.

I don't have time right now to work on this; so, I'd recommend that either you try to fix it yourself (in which case, please make a pull request); or simply use an older version of Keras. If you decide to do the latter, I can give you a hand finding a working version.

Btw, Keras transfers your dataset minibatch-by-minibatch from CPU to GPU memory, so bigger-than-GPU mem datasets should already work.

**Comment by elbamos** [comment]
Thanks!

I think an earlier version of keras would be a good idea, if you can recommend one.

Regarding the batches --- I want to use very small batches , but isn't it more efficient to transfer the data for a lot of batches to the GPU at once?

**Comment by wuaalb** [comment]
Try the my fork of Keras (which doesn't contain any changes, but just is an older version which should work with this package).

I've also pushed some small updates to keras_extensions.

About the efficiency of data transfer; in my case it was only a little slower, and avoids out-of-memory problems on smaller GPUs. If you want to change this; you'd have to change Keras internals though.

**Comment by elbamos** [comment]
Thanks!  I have it running now.

Regarding the data transfer -- this is one of those cases, where I'm just gonna say "thank for saving me what would have been a great deal of lost time trying to diagnose why training was going so slowly."

I still have to do something with the issue.  My data is a sparse matrix that, if dense, would not fit into *main* memory.  So I have to convert it to dense in chunks. 

What I'm doing is calling fit( nb_epoch = 1) in loop.

**Comment by elbamos** [comment]
FYI - I took a look at theano_untils.  This is fixed by changing RBM.py to import zeros from keras.backend and call zeros() instead of shared_zeros().

However, it looks like there may be some other differences between your keras and keras-trunk that create other issues.

**Comment by elbamos** [comment]
I gave in and made a PR.
